---
title: "CompBio_Lecture_Notes_03092017"
author: "Emily Mikucki"
date: "March 9, 2017"
output: html_document
---
###**Illustration of structured programming**
```{r}
##################################################################################################
# FUNCTION: GetData
# Read in a csv file 
# Input: csv file
# Output: data frame
# ________________________________________________________________________________________________
GetData <- function(fileName=NULL) {
if(is.null(fileName)) {
  dataFrame <- data.frame(ID=1:10, varA<-runif(10), varB<-runif(10))
} else {
  dataFrame <- read.table(file = fileName, 
                          header=TRUE,
                          sep=",",
                          stringsAsFactors = FALSE)
}
return(dataFrame)
}
GetData()
```

```{r}
##################################################################################################
# FUNCTION: FitRegressionModel
# Fits an ordinary least squares regression
# Input: x and y numeric vectors of same length 
# Output: entire  model summary structure from lm 
# _______________________________________________________________________________________________
FitRegressionModel <- function(xVar=runif(10),
                               yVar=runif(10)) {
  dataFrame <- data.frame(xVar,yVar)
  regModel <- lm(yVar~xVar, data=dataFrame)
return(summary(regModel))
}
```

```{r}
##################################################################################################
# FUNCTION: SummarizeOutput
# pull elements from lm model summary list
# Input: list from model summary call of lm
# Output: vector of regression residuals 
# ________________________________________________________________________________________________
SummarizeOutput <- function(z=NULL) {
if(is.null(z)) {
  z <- summary(lm(runif(10)~runif(10)))
}
  
return(z$residuals)
  
}
```

```{r}
##################################################################################################
# FUNCTION: GraphResults
# Graph data and fitted OLS line 
# Input: x and y vectors of numeric. same length. 
# Output: creates graph 
# ________________________________________________________________________________________________
GraphResults <- function(xVar=runif(10),
                         yVar=runif(10)){
dataFrame <- data.frame(xVar,yVar)
plot(y=dataFrame$yVar, x=dataFrame$xVar, pch=21, bg="lightblue", cex=2)
regModel <- lm(yVar~xVar, data=dataFrame)
abline(regModel)
  
message("Message: Regression graph created")
}
GraphResults()



#_____________________________________________
#Global variables 
antFile <- "antcountydata.csv" #New England ant data 
xCol <- 7 #column 7 = latitude centroid of county
yCol <- 5 #column 5 = number of ant species 
#_____________________________________________


#Program Body
temp1 <- GetData(fileName = antFile) #constructs dataframe
x<- temp1[,xCol]
y <- temp1[,yCol]  
temp2 <- FitRegressionModel(xVar=x, yVar=y)
temp3 <- SummarizeOutput(temp2)
GraphResults(xVar = x, yVar = y)

print(temp3)
print(temp2)
```

