---
title: "CompBio_Lecture_Notes_03092017"
author: "Emily Mikucki"
date: "March 9, 2017"
output: html_document
---
###**Illustration of structured programming**
```{r}
##################################################################################################
# FUNCTION: GetData
# One Line Description
# Input: x
# Output: x
# ________________________________________________________________________________________________
GetData <- function() {

return("testing.......GetData")
}
```

```{r}
##################################################################################################
# FUNCTION: CalculateStuff
# One Line Description
# Input: x
# Output: x
# ________________________________________________________________________________________________
CalculateStuff <- function() {

return("testing.......CalculateStuff")
}
```

```{r}
##################################################################################################
# FUNCTION: SummarizeOutput
# One Line Description
# Input: x
# Output: x
# ________________________________________________________________________________________________
SummarizeOutput <- function() {

return("testing.......SummarizeOutput")
}
```

```{r}
##################################################################################################
# FUNCTION: GraphResults
# One Line Description
# Input: x
# Output: x
# ________________________________________________________________________________________________
GraphResults <- function() {

return("testing.......GraphResults")
}
```





